### ISSUE TITLE
Opdracht 1.2

### ISSUE THREAD

**Issue by pp-koch** [DanielvandeVelde/browser-technologies-1920#1]
* een beschrijving van alle features die je hebt getest

	Zeer volledig.
	Het enige wat ontbreekt is een link naar de WAFS opdracht. Kan je die nog toevoegen?

* een beschrijving van de Devices en browsers waar je op hebt getest

	Deze ontbreekt. Je hebt duidelijk op verschillende devices gekeken en problemen en oplossingen gevonden, maar ik weet niet welke. Kan je die nog toevoegen?

* een beschrijving van de screenreader test

	Deze ontbreekt. Kan je hem nog toevoegen?

* beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben

	Uitstekende, zeer volledige lijst. 

	Je hebt deze opdracht voor 90% af; alleen de laatste kleinigheden ontbreken nog.

**Comment by DanielvandeVelde** [comment]
> Het enige wat ontbreekt is een link naar de WAFS opdracht. Kan je die nog toevoegen?

Toegevoegd!

> een beschrijving van de Devices en browsers waar je op hebt getest

Toegevoegd en dankzij de de afbeeldingen die ik vergeten was toe te voegen heb ik dit stuk ook nog wat kunnen uitbreiden.

> een beschrijving van de screenreader test.   

De screenreader test was een pijnlijke ervaring. Toegevoegd en wat meer over geschreven waarom het een eye-opener was.

**Comment by pp-koch** [comment]
Prima; deze opdracht is af. Als dit een echte opdracht voor een klant was, zou je het screenreader-gedeelte nog moeten afmaken, maar dat laten we nu maar even zitten. Je hebt wel de correcte oplossingen geschetst.

Geslaagd.

**Comment by DanielvandeVelde** [comment]
Ik ben toevallig gister bezig geweest in mijn Progressive Web App om er voor te zorgen dat er een alternatief is voor de grafiek voor zowel de 'geen javascript'-gebruikers als voor de gebruikers van een screenreader.
Niet heel belangrijk, maar ik doe zeker m'n best om overal rekening mee te houden en dit dus te implementeren.
Ik zal dit morgen ook even uitgebreid beschrijven in de mijn readme van deze repo :-)

[Demo](https://cryptocurrency-1920.herokuapp.com/coin/BTC)
